name: "MY JF TEST"
on: [ push, pull_request ]
jobs:
  Jf-test:
    name: Test my jf command
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - run: |
         CD npm-example
         jf rt ping  
